telegram:
  bot:
    username: "BirdCallsBot"
    token: ${BOT_TOKEN}
    birds:
      "[Mallard]":
        "de": "Stockente"
        "ru": "Дикая утка"
      "[Snow goose]":
        "de": "Schneegans"
        "ru": "Снежный гусь"
      "[Chicken]":
        "de": "Haushuhn"
        "ru": "Курица"
      "[Black grouse]":
        "de": "Birkhuhn"
        "ru": "Тетерев-косач"
      "[Rock bunting]":
        "de": "Zippammer"
        "ru": "Горная овсянка"
      "[Twite]":
        "de": "Berghänfling"
        "ru": "Горная коноплянка"
      "[Green warbler]":
        "de": "Wacholderlaubsänger"
        "ru": "Желтобрюхая пеночка"
      "[Coal tit]":
        "de": "Tannenmeise"
        "ru": "Черная синица"
      "[Isabelline shrike]":
        "de": "Isabellwürger"
        "ru": "Буланый жулан"
      "[Red-eyed vireo]":
        "de": "Rotaugenvireo"
        "ru": "Красноглазый виреон"
      "[Merlin]":
        "de": "Merlin"
        "ru": "Дербник"
      "[Tawny owl]":
        "de": "Waldkauz"
        "ru": "Серая неясыть"